"""Revenue Cloud action registry derived from the local guide and source image."""

DEFAULT_API_VERSION = "latest"
DEFAULT_TARGET_ORG = None

TARGET_ORG_DESCRIPTION = (
    "Salesforce org alias or username. Defaults to SALESFORCE_TARGET_ORG or SF_TARGET_ORG."
)

CONTROL_FIELDS = {
    "input",
    "inputs",
    "target_org",
    "api_version",
    "validate_only",
}


ACTION_REGISTRY = {
    "createContract": {
        "domain": "Transaction Management",
        "api_name": "createContract",
        "since": "60.0",
        "description": "Create a contract from a quote or order.",
        "required": ["sourceId"],
        "optional": ["contractPriceOption"],
        "properties": {
            "sourceId": {"type": "string", "description": "ID of the quote or order."},
            "contractPriceOption": {
                "type": "string",
                "description": "CONTRACT_HEADER_ONLY, NET_UNIT_PRICE_ONLY, or DISCOUNT_ONLY.",
            },
        },
    },
    "createOrderFromQuote": {
        "domain": "Transaction Management",
        "api_name": "createOrderFromQuote",
        "since": "60.0",
        "description": "Create an order from a quote record.",
        "required": ["quoteRecordId"],
        "optional": [],
        "properties": {
            "quoteRecordId": {"type": "string", "description": "ID of the quote record."},
        },
    },
    "createOrdersFromQuote": {
        "domain": "Transaction Management",
        "api_name": "createOrdersFromQuote",
        "since": "65.0",
        "description": "Create multiple orders from a single quote.",
        "required": [],
        "optional": [],
        "properties": {},
    },
    "createOrUpdateAssetFromOrder": {
        "domain": "Transaction Management",
        "api_name": "createOrUpdateAssetFromOrder",
        "since": "60.0",
        "description": "Create or update assets for all order items in an order.",
        "required": ["orderId"],
        "optional": [],
        "properties": {
            "orderId": {"type": "string", "description": "ID of the order."},
        },
    },
    "createOrUpdateAssetFromOrderItem": {
        "domain": "Transaction Management",
        "api_name": "createOrUpdateAssetFromOrderItem",
        "since": "60.0",
        "description": "Create or update assets from individual order items.",
        "required": ["orderItemIds"],
        "optional": [],
        "properties": {
            "orderItemIds": {
                "type": "array",
                "items": {"type": "string"},
                "description": "Order item IDs to assetize.",
            },
        },
    },
    "getRenewableAssetsSummary": {
        "domain": "Transaction Management",
        "api_name": "getRenewableAssetsSummary",
        "since": "64.0",
        "description": "Retrieve renewable asset details for an order.",
        "required": [],
        "optional": [],
        "properties": {},
    },
    "initiateAmendment": {
        "domain": "Transaction Management",
        "api_name": "initiateAmendment",
        "since": "60.0",
        "description": "Initiate and execute an asset amendment.",
        "required": ["amendAssetIds", "amendStartDate", "amendOutputType", "quantityChange"],
        "optional": ["amendContractId", "amendOpportunityId", "skipPricing"],
        "properties": {
            "amendAssetIds": {"type": "array", "items": {"type": "string"}},
            "amendStartDate": {"type": "string", "description": "ISO datetime."},
            "amendOutputType": {"type": "string", "description": "Quote or Order."},
            "quantityChange": {"type": "number"},
            "amendContractId": {"type": "string"},
            "amendOpportunityId": {"type": "string"},
            "skipPricing": {"type": "boolean"},
        },
    },
    "initiateCancellation": {
        "domain": "Transaction Management",
        "api_name": "initiateCancellation",
        "since": "60.0",
        "description": "Initiate and execute an asset cancellation.",
        "required": ["cancelAssetIds", "cancelStartDate", "cancelOutputType"],
        "optional": ["cancelContractId", "cancelOpportunityId", "skipPricing"],
        "properties": {
            "cancelAssetIds": {"type": "array", "items": {"type": "string"}},
            "cancelStartDate": {"type": "string", "description": "ISO datetime."},
            "cancelOutputType": {"type": "string", "description": "Quote or Order."},
            "cancelContractId": {"type": "string"},
            "cancelOpportunityId": {"type": "string"},
            "skipPricing": {"type": "boolean"},
        },
    },
    "initiateRenewal": {
        "domain": "Transaction Management",
        "api_name": "initiateRenewal",
        "since": "60.0",
        "description": "Initiate and execute an asset renewal.",
        "required": ["renewAssetIds", "renewOutputType"],
        "optional": ["renewContractId", "renewOpportunityId", "renewStartDate", "renewEndDate", "skipPricing"],
        "properties": {
            "renewAssetIds": {"type": "array", "items": {"type": "string"}},
            "renewOutputType": {"type": "string", "description": "Quote or Order."},
            "renewContractId": {"type": "string"},
            "renewOpportunityId": {"type": "string"},
            "renewStartDate": {"type": "string", "description": "ISO datetime."},
            "renewEndDate": {"type": "string", "description": "ISO datetime."},
            "skipPricing": {"type": "boolean"},
        },
    },
    "initiateRollBackLastAction": {
        "domain": "Transaction Management",
        "api_name": "initiateRollBackLastAction",
        "since": "65.0",
        "description": "Reverse the last future-dated amendment or renewal on assets.",
        "required": ["assetIds", "outputType"],
        "optional": [],
        "properties": {
            "assetIds": {"type": "array", "items": {"type": "string"}},
            "outputType": {"type": "string", "description": "Quote or Order."},
        },
    },
    "initiateTransfer": {
        "domain": "Transaction Management",
        "api_name": "initiateTransfer",
        "since": "65.0",
        "description": "Transfer assets from one account to another.",
        "required": ["transferRecords", "transferDate", "targetAccountId", "outputRecordType"],
        "optional": ["targetContractId", "shouldSkipPricing"],
        "properties": {
            "transferRecords": {
                "type": "array",
                "items": {"type": "object"},
                "description": "Records with assetId and transferQuantity.",
            },
            "transferDate": {"type": "string", "description": "ISO datetime."},
            "targetAccountId": {"type": "string"},
            "targetContractId": {"type": "string"},
            "outputRecordType": {"type": "string", "description": "Quote or Order."},
            "shouldSkipPricing": {"type": "boolean"},
        },
    },
    "executeQualificationProcedure": {
        "domain": "Product Catalog Management",
        "api_name": "executeQualificationProcedure",
        "since": "64.0",
        "description": "Execute qualification for specified products.",
        "required": ["productIds"],
        "optional": [
            "additionalContextData",
            "contextDefinitionName",
            "contextMappingName",
            "correlationId",
            "qualificationProcedureName",
            "userContextInputRepresentation",
        ],
        "properties": {
            "productIds": {"type": "array", "items": {"type": "string"}},
            "additionalContextData": {"type": "object"},
            "contextDefinitionName": {"type": "string"},
            "contextMappingName": {"type": "string"},
            "correlationId": {"type": "string"},
            "qualificationProcedureName": {"type": "string"},
            "userContextInputRepresentation": {"type": "object"},
        },
    },
    "getMultipleProductDetails": {
        "domain": "Product Catalog Management",
        "api_name": "getMultipleProductDetails",
        "since": "64.0",
        "description": (
            "Get details for a list of products. The Apex BulkProductDetailsInput exposes the "
            "field 'productData' (list of product input bodies). The MCP wrapper accepts either "
            "'productData' or the legacy alias 'productDataInputs' and normalizes to 'productData'."
        ),
        "required": ["productData"],
        "optional": [
            "additionalContextData",
            "additionalFields",
            "catalogId",
            "contextDefinitionName",
            "contextMappingName",
            "correlationId",
            "currencyCode",
            "enablePricing",
            "enableQualificationProcedure",
            "priceBookId",
            "pricingProcedureName",
            "qualificationProcedureName",
            "userContextInputRepresentation",
        ],
        "properties": {
            "productData": {
                "type": "array",
                "items": {
                    "type": "object",
                    "properties": {
                        "productId": {"type": "string"},
                        "quantity": {"type": "number"},
                        "productSellingModelId": {"type": "string"},
                        "attributes": {"type": "object"},
                    },
                },
                "description": "List of product input bodies (productId required per item).",
            },
            "productDataInputs": {
                "type": "array",
                "items": {"type": "object"},
                "description": "Deprecated alias of productData. Will be normalized to productData.",
            },
            "additionalContextData": {"type": "object"},
            "additionalFields": {"type": "object"},
            "catalogId": {"type": "string"},
            "contextDefinitionName": {"type": "string"},
            "contextMappingName": {"type": "string"},
            "correlationId": {"type": "string"},
            "currencyCode": {"type": "string"},
            "enablePricing": {"type": "boolean"},
            "enableQualificationProcedure": {"type": "boolean"},
            "priceBookId": {"type": "string"},
            "pricingProcedureName": {"type": "string"},
            "qualificationProcedureName": {"type": "string"},
            "userContextInputRepresentation": {"type": "object"},
        },
    },
    "runSalesforcePricing": {
        "domain": "Salesforce Pricing",
        "api_name": "runSalesforcePricing",
        "since": "60.0",
        "description": "Invoke Salesforce Pricing by context and pricing procedure.",
        "required": ["contextInstanceId", "pricingProcedureName"],
        "optional": ["discoveryProcedure", "effectiveDate", "isDeveloperName", "isSkipWaterfall", "skipDiscovery"],
        "properties": {
            "contextInstanceId": {"type": "string"},
            "pricingProcedureName": {"type": "string"},
            "discoveryProcedure": {"type": "string"},
            "effectiveDate": {"type": "string", "description": "ISO datetime."},
            "isDeveloperName": {"type": "boolean"},
            "isSkipWaterfall": {"type": "boolean"},
            "skipDiscovery": {"type": "boolean"},
        },
    },
    "runConfigRules": {
        "domain": "Product Configurator",
        "api_name": "runConfigRules",
        "since": "65.0",
        "description": "Run product configuration rules for a transaction.",
        "required": ["transactionId"],
        "optional": ["transactionContextId"],
        "properties": {
            "transactionId": {"type": "string"},
            "transactionContextId": {"type": "string"},
        },
    },
    "invokeRatingService": {
        "domain": "Rate Management",
        "api_name": "invokeRatingService",
        "since": "62.0",
        "description": "Rate usage records through the rating service.",
        "required": ["recordID", "contextDefinitionId"],
        "optional": [
            "attributeRateCardID",
            "baseRateCardID",
            "contextMappingID",
            "isSkipWaterfall",
            "procedureName",
            "tierRateCardID",
        ],
        "properties": {
            "recordID": {"type": "string", "description": "Usage ratable summary record ID."},
            "recordIDs": {"type": "string", "description": "Alias used by examples in the guide."},
            "contextDefinitionId": {"type": "string"},
            "contextMappingID": {"type": "string"},
            "contextMappingId": {"type": "string"},
            "procedureName": {"type": "string"},
            "isSkipWaterfall": {"type": "boolean"},
            "baseRateCardID": {"type": "string"},
            "tierRateCardID": {"type": "string"},
            "attributeRateCardID": {"type": "string"},
        },
    },
    "rateUsageRecords": {
        "domain": "Rate Management",
        "api_name": "invokeRatingService",
        "since": "62.0",
        "description": "Image command alias for invokeRatingService.",
        "required": ["recordID", "contextDefinitionId"],
        "optional": [
            "attributeRateCardID",
            "baseRateCardID",
            "contextMappingID",
            "isSkipWaterfall",
            "procedureName",
            "tierRateCardID",
        ],
        "properties": {},
    },
    "processConsumptionOverages": {
        "domain": "Usage Management",
        "api_name": "processConsumptionOverages",
        "since": "63.0",
        "description": "Process overages for a usage ratable summary record.",
        "required": ["usageRatableSummaryId"],
        "optional": [],
        "properties": {
            "usageRatableSummaryId": {"type": "string"},
        },
    },
    "createServiceDocument": {
        "domain": "Transaction Management",
        "api_name": "createServiceDocument",
        "since": None,
        "description": "Create service documents from a record and service document template.",
        "required": ["recordId", "templateId"],
        "optional": ["title", "locale", "documentType", "pdfReportId"],
        "properties": {
            "recordId": {"type": "string", "description": "ID of the record to print."},
            "templateId": {"type": "string", "description": "ID of the flexipage service document template."},
            "title": {"type": "string", "description": "Document title."},
            "locale": {"type": "string", "description": "Locale used to create the document."},
            "documentType": {"type": "string", "description": "Feature document type."},
            "pdfReportId": {"type": "string", "description": "Existing PDF report ID, when applicable."},
        },
    },
    # ----- Orders / Orchestration -----
    "decomposeSalesTransaction": {
        "domain": "Orders",
        "api_name": "decomposeSalesTransaction",
        "since": "66.0",
        "description": "Decompose a sales transaction into fulfillment items.",
        "required": ["salesTransactionId", "fulfillmentAdapter"],
        "optional": ["hydratedContextId", "intakeRequestType", "fulfillmentPriority", "priorityLimitAction", "allowOverrideOfPointOfNoReturn"],
        "properties": {
            "salesTransactionId": {"type": "string"},
            "hydratedContextId": {"type": "string"},
            "intakeRequestType": {"type": "string"},
            "fulfillmentAdapter": {"type": "string"},
            "fulfillmentPriority": {"type": "string"},
            "priorityLimitAction": {"type": "string"},
            "allowOverrideOfPointOfNoReturn": {"type": "boolean"},
        },
    },
    "orchestrateSalesTransaction": {
        "domain": "Orders",
        "api_name": "orchestrateSalesTransaction",
        "since": "67.0",
        "description": "Orchestrate fulfillment for a sales transaction (decompose + handoff).",
        "required": ["salesTransactionId", "fulfillmentAdapter"],
        "optional": ["hydratedContextId", "intakeRequestType", "fulfillmentPriority", "priorityLimitAction", "allowOverrideOfPointOfNoReturn"],
        "properties": {
            "salesTransactionId": {"type": "string"},
            "hydratedContextId": {"type": "string"},
            "intakeRequestType": {"type": "string"},
            "fulfillmentAdapter": {"type": "string"},
            "fulfillmentPriority": {"type": "string"},
            "priorityLimitAction": {"type": "string"},
            "allowOverrideOfPointOfNoReturn": {"type": "boolean"},
        },
    },
    "orchestrateTransaction": {
        "domain": "Orders",
        "api_name": "orchestrateTransaction",
        "since": "67.0",
        "description": "Generic transaction orchestration entry point.",
        "required": ["transactionId", "orchestrationType"],
        "optional": [],
        "properties": {
            "transactionId": {"type": "string"},
            "orchestrationType": {"type": "string"},
        },
    },
    "submitSalesTransaction": {
        "domain": "Orders",
        "api_name": "submitSalesTransaction",
        "since": "67.0",
        "description": "Submit a sales transaction for processing.",
        "required": ["salesTransactionId"],
        "optional": ["hydratedContextId", "intakeRequestType", "fulfillmentAdapter", "fulfillmentPriority", "priorityLimitAction", "allowOverrideOfPointOfNoReturn"],
        "properties": {
            "salesTransactionId": {"type": "string"},
            "hydratedContextId": {"type": "string"},
            "intakeRequestType": {"type": "string"},
            "fulfillmentAdapter": {"type": "string"},
            "fulfillmentPriority": {"type": "string"},
            "priorityLimitAction": {"type": "string"},
            "allowOverrideOfPointOfNoReturn": {"type": "boolean"},
        },
    },
    "freezeSalesTransaction": {
        "domain": "Orders",
        "api_name": "freezeSalesTransaction",
        "since": "67.0",
        "description": "Freeze a sales transaction. Requires v67.0+.",
        "required": ["salesTransactionId"],
        "optional": [],
        "properties": {"salesTransactionId": {"type": "string"}},
    },
    "unfreezeSalesTransaction": {
        "domain": "Orders",
        "api_name": "unfreezeSalesTransaction",
        "since": "67.0",
        "description": "Unfreeze a sales transaction. Requires v67.0+.",
        "required": ["salesTransactionId"],
        "optional": [],
        "properties": {"salesTransactionId": {"type": "string"}},
    },
    # ----- CPQ extras -----
    "runSalesforceHeadlessPricing": {
        "domain": "Salesforce Pricing",
        "api_name": "runSalesforceHeadlessPricing",
        "since": "67.0",
        "description": "Execute pricing without a context instance, suitable for the Pricing Connect API.",
        "required": ["contextDefinitionId", "contextMappingId", "pricingProcedureId", "pricingData"],
        "optional": ["isSkipWaterfall", "useSessionScopedContext", "persistContext", "taggedData", "discoveryProcedure", "skipDiscovery", "effectiveDate", "displayContext", "isHighVolumeLineItems"],
        "properties": {
            "contextDefinitionId": {"type": "string"},
            "contextMappingId": {"type": "string"},
            "pricingProcedureId": {"type": "string"},
            "pricingData": {"type": "string", "description": "JSON string with the pricing payload."},
            "isSkipWaterfall": {"type": "boolean"},
            "useSessionScopedContext": {"type": "boolean"},
            "persistContext": {"type": "boolean"},
            "taggedData": {"type": "boolean"},
            "discoveryProcedure": {"type": "string"},
            "skipDiscovery": {"type": "boolean"},
            "effectiveDate": {"type": "string"},
            "displayContext": {"type": "boolean"},
            "isHighVolumeLineItems": {"type": "boolean"},
        },
    },
    "invokeSummaryCreationService": {
        "domain": "Usage Management",
        "api_name": "invokeSummaryCreationService",
        "since": "67.0",
        "description": "Create a usage entitlement summary for a given account.",
        "required": ["usageEntitlementAccountId"],
        "optional": [],
        "properties": {"usageEntitlementAccountId": {"type": "string"}},
    },
    # ----- Asset / Usage entitlement extras -----
    "refreshUsageEntitlementBucket": {
        "domain": "Usage Management",
        "api_name": "refreshUsageEntitlementBucket",
        "since": "66.0",
        "description": "Refresh a transaction usage entitlement bucket.",
        "required": ["transactionUsageEntitlementId"],
        "optional": [],
        "properties": {"transactionUsageEntitlementId": {"type": "string"}},
    },
    "retriggerEntlCreaProc": {
        "domain": "Usage Management",
        "api_name": "retriggerEntlCreaProc",
        "since": "66.0",
        "description": "Retrigger entitlement creation procedure for an asset.",
        "required": ["assetId"],
        "optional": [],
        "properties": {"assetId": {"type": "string"}},
    },
    # ----- Approvals -----
    "cancelApprovalSubmission": {
        "domain": "Approvals",
        "api_name": "cancelApprovalSubmission",
        "since": "66.0",
        "description": "Cancel an RC ApprovalSubmission (prefix '9j8'). NOTE: this is the Revenue Cloud Approvals stack, not the platform-wide Approval Process. For standard Salesforce approvals (ProcessInstanceWorkitem '04i') use salesforce_rest_request to POST /process/approvals.",
        "required": ["approvalSubmissionId"],
        "optional": ["comments"],
        "properties": {"approvalSubmissionId": {"type": "string"}, "comments": {"type": "string"}},
    },
    "recallApprovalSubmission": {
        "domain": "Approvals",
        "api_name": "recallApprovalSubmission",
        "since": "66.0",
        "description": "Recall a submitted RC ApprovalSubmission ('9j8'). For standard SF approvals use salesforce_rest_request to POST /process/approvals with actionType=Removed.",
        "required": ["approvalSubmissionId"],
        "optional": ["comments"],
        "properties": {"approvalSubmissionId": {"type": "string"}, "comments": {"type": "string"}},
    },
    "reviewApprovalWorkItem": {
        "domain": "Approvals",
        "api_name": "reviewApprovalWorkItem",
        "since": "66.0",
        "description": "Approve or reject an RC ApprovalWorkItem (prefix '9jR'). For standard SF ProcessInstanceWorkitem ('04i') use salesforce_rest_request to POST /process/approvals.",
        "required": ["approvalWorkItemId", "approvalDecision"],
        "optional": ["comments", "channelType"],
        "properties": {
            "approvalWorkItemId": {"type": "string"},
            "approvalDecision": {"type": "string", "description": "Approve, Reject, etc."},
            "comments": {"type": "string"},
            "channelType": {"type": "string"},
        },
    },
    "overrideApprovalWorkItem": {
        "domain": "Approvals",
        "api_name": "overrideApprovalWorkItem",
        "since": "66.0",
        "description": "Override the decision on an RC ApprovalWorkItem ('9jR'). RC-only — does not act on standard SF ProcessInstanceWorkitem.",
        "required": ["approvalWorkItemId", "approvalDecision"],
        "optional": ["comments", "channelType"],
        "properties": {
            "approvalWorkItemId": {"type": "string"},
            "approvalDecision": {"type": "string"},
            "comments": {"type": "string"},
            "channelType": {"type": "string"},
        },
    },
    "reassignApprovalWorkItem": {
        "domain": "Approvals",
        "api_name": "reassignApprovalWorkItem",
        "since": "66.0",
        "description": "Reassign an RC ApprovalWorkItem ('9jR') to a different user or queue. RC-only.",
        "required": ["approvalWorkItemId", "assigneeId"],
        "optional": ["comments"],
        "properties": {
            "approvalWorkItemId": {"type": "string"},
            "assigneeId": {"type": "string"},
            "comments": {"type": "string"},
        },
    },
    "getPreviousRelaRecDetails": {
        "domain": "Approvals",
        "api_name": "getPreviousRelaRecDetails",
        "since": "66.0",
        "description": "Fetch related-record details for prior approval orchestration steps.",
        "required": ["flowOrchestrationInstanceId", "stepApiNamesList"],
        "optional": [],
        "properties": {
            "flowOrchestrationInstanceId": {"type": "string"},
            "stepApiNamesList": {
                "type": "array",
                "items": {"type": "string"},
                "description": "Up to 100 step API names.",
            },
        },
    },
    # ----- Billing - available on most orgs -----
    "applyPaymentsAndCreditsByRules": {
        "domain": "Payments",
        "api_name": "applyPaymentsAndCreditsByRules",
        "since": "66.0",
        "description": "Apply outstanding payments and credits to invoices for an account using configured rules.",
        "required": ["accountId"],
        "optional": ["targetDate"],
        "properties": {
            "accountId": {"type": "string"},
            "targetDate": {"type": "string", "description": "ISO date."},
        },
    },
    "blngSvcExtendInvoiceDueDate": {
        "domain": "Billing",
        "api_name": "blngSvcExtendInvoiceDueDate",
        "since": "66.0",
        "description": "Extend the due date of an invoice.",
        "required": ["invoiceId", "revisedDueDateTime"],
        "optional": [],
        "properties": {
            "invoiceId": {"type": "string"},
            "revisedDueDateTime": {"type": "string", "description": "ISO date."},
        },
    },
    "blngSvcSuspendBilling": {
        "domain": "Billing",
        "api_name": "blngSvcSuspendBilling",
        "since": "66.0",
        "description": "Suspend billing for an account between two dates.",
        "required": ["accountId", "suspensionDate", "resumptionDate"],
        "optional": [],
        "properties": {
            "accountId": {"type": "string"},
            "suspensionDate": {"type": "string", "description": "ISO date."},
            "resumptionDate": {"type": "string", "description": "ISO date."},
        },
    },
    "blngSvcUpdateBillToContact": {
        "domain": "Billing",
        "api_name": "blngSvcUpdateBillToContact",
        "since": "66.0",
        "description": "Update the Bill-To contact on an invoice.",
        "required": ["invoiceId", "newBillToContactId"],
        "optional": ["setAsDefault"],
        "properties": {
            "invoiceId": {"type": "string"},
            "newBillToContactId": {"type": "string"},
            "setAsDefault": {"type": "boolean"},
        },
    },
    "createInvoiceFromChangeOrders": {
        "domain": "Billing",
        "api_name": "createInvoiceFromChangeOrders",
        "since": "66.0",
        "description": "Create an invoice from change orders.",
        "required": ["createInvoiceFromChangeOrdersInput"],
        "optional": [],
        "properties": {
            "createInvoiceFromChangeOrdersInput": {
                "type": "object",
                "description": "Wrapper input describing the change orders to invoice.",
            }
        },
    },
    "createInvoiceFromFulfillmentOrder": {
        "domain": "Billing",
        "api_name": "createInvoiceFromFulfillmentOrder",
        "since": "66.0",
        "description": "Create an invoice from a fulfillment order.",
        "required": ["fulfillmentOrderId"],
        "optional": [],
        "properties": {"fulfillmentOrderId": {"type": "string"}},
    },
    # ----- Billing v67.0 actions (registered for orgs running v67.0; describe returns 404 on older orgs) -----
    "postDraftInvoice": {
        "domain": "Billing",
        "api_name": "postDraftInvoice",
        "since": "67.0",
        "description": "Post a draft invoice. Requires v67.0+ Billing license.",
        "required": ["invoiceId"],
        "optional": [],
        "properties": {"invoiceId": {"type": "string"}},
    },
    "postDraftInvoiceBatchRun": {
        "domain": "Billing",
        "api_name": "postDraftInvoiceBatchRun",
        "since": "67.0",
        "description": "Post draft invoices in batch. Requires v67.0+.",
        "required": ["invoiceBatchRunId"],
        "optional": [],
        "properties": {"invoiceBatchRunId": {"type": "string"}},
    },
    "postDraftCreditMemo": {
        "domain": "Billing",
        "api_name": "postDraftCreditMemo",
        "since": "67.0",
        "description": "Post a draft credit memo. Requires v67.0+.",
        "required": ["creditMemoId"],
        "optional": [],
        "properties": {"creditMemoId": {"type": "string"}},
    },
    "voidPostedCreditMemo": {
        "domain": "Billing",
        "api_name": "voidPostedCreditMemo",
        "since": "67.0",
        "description": "Void a posted credit memo. Requires v67.0+.",
        "required": ["creditMemoId"],
        "optional": ["voidReason"],
        "properties": {"creditMemoId": {"type": "string"}, "voidReason": {"type": "string"}},
    },
    "generateInvoiceDocuments": {
        "domain": "Billing",
        "api_name": "generateInvoiceDocuments",
        "since": "67.0",
        "description": "Generate PDF documents for invoices asynchronously. Requires v67.0+.",
        "required": ["invoiceIds"],
        "optional": ["templateId"],
        "properties": {
            "invoiceIds": {"type": "array", "items": {"type": "string"}},
            "templateId": {"type": "string"},
        },
    },
    "applyCredit": {
        "domain": "Payments",
        "api_name": "applyCredit",
        "since": "67.0",
        "description": "Apply a credit memo or line to an invoice. Requires v67.0+.",
        "required": ["creditMemoId", "invoiceId"],
        "optional": ["amount"],
        "properties": {
            "creditMemoId": {"type": "string"},
            "invoiceId": {"type": "string"},
            "amount": {"type": "number"},
        },
    },
    "applyPayment": {
        "domain": "Payments",
        "api_name": "applyPayment",
        "since": "67.0",
        "description": "Apply a payment to an invoice via PaymentLineInvoice. Requires v67.0+.",
        "required": ["paymentId", "invoiceId"],
        "optional": ["amount"],
        "properties": {
            "paymentId": {"type": "string"},
            "invoiceId": {"type": "string"},
            "amount": {"type": "number"},
        },
    },
    "unapplyPayment": {
        "domain": "Payments",
        "api_name": "unapplyPayment",
        "since": "67.0",
        "description": "Reverse an applied payment. Requires v67.0+.",
        "required": ["paymentLineInvoiceId"],
        "optional": [],
        "properties": {"paymentLineInvoiceId": {"type": "string"}},
    },
    "unapplyCredit": {
        "domain": "Payments",
        "api_name": "unapplyCredit",
        "since": "67.0",
        "description": "Reverse an applied credit. Requires v67.0+.",
        "required": ["creditMemoApplicationId"],
        "optional": [],
        "properties": {"creditMemoApplicationId": {"type": "string"}},
    },
    "paymentSale": {
        "domain": "Payments",
        "api_name": "paymentSale",
        "since": "67.0",
        "description": "Capture a payment without prior authorization. Requires v67.0+.",
        "required": ["paymentMethodId", "amount"],
        "optional": ["currencyIsoCode", "comments"],
        "properties": {
            "paymentMethodId": {"type": "string"},
            "amount": {"type": "number"},
            "currencyIsoCode": {"type": "string"},
            "comments": {"type": "string"},
        },
    },
    "writeOffInvoices": {
        "domain": "Billing",
        "api_name": "writeOffInvoices",
        "since": "67.0",
        "description": "Write off one or more invoices. Requires v67.0+.",
        "required": ["invoiceIds"],
        "optional": ["reason"],
        "properties": {
            "invoiceIds": {"type": "array", "items": {"type": "string"}},
            "reason": {"type": "string"},
        },
    },
    "generateAccountStatement": {
        "domain": "Billing",
        "api_name": "generateAccountStatement",
        "since": "67.0",
        "description": "Generate an account statement document. Requires v67.0+.",
        "required": ["accountId"],
        "optional": ["asOfDate"],
        "properties": {
            "accountId": {"type": "string"},
            "asOfDate": {"type": "string", "description": "ISO date."},
        },
    },
    "createBillingSchedulesFromBillingTransaction": {
        "domain": "Billing",
        "api_name": "createBillingSchedulesFromBillingTransaction",
        "since": "67.0",
        "description": "Create billing schedules from a billing transaction. Requires v67.0+.",
        "required": ["billingTransactionId"],
        "optional": [],
        "properties": {"billingTransactionId": {"type": "string"}},
    },
    "recoverBillingSchedules": {
        "domain": "Billing",
        "api_name": "recoverBillingSchedules",
        "since": "67.0",
        "description": "Recover failed billing schedules. Requires v67.0+.",
        "required": ["billingScheduleIds"],
        "optional": [],
        "properties": {
            "billingScheduleIds": {"type": "array", "items": {"type": "string"}},
        },
    },
}


def action_names():
    return sorted(ACTION_REGISTRY.keys())


def action_metadata(name):
    meta = ACTION_REGISTRY.get(name)
    if not meta:
        raise KeyError("Unknown Revenue Cloud action: %s" % name)
    merged = dict(meta)
    if not merged.get("properties") and merged["api_name"] in ACTION_REGISTRY:
        merged["properties"] = ACTION_REGISTRY[merged["api_name"]].get("properties", {})
    return merged


def action_input_schema(name):
    meta = action_metadata(name)
    properties = {
        "target_org": {
            "type": "string",
            "description": TARGET_ORG_DESCRIPTION,
        },
        "api_version": {
            "type": "string",
            "description": "Salesforce API version without leading v, or latest (default).",
        },
        "validate_only": {
            "type": "boolean",
            "description": "If true, describe the action endpoint instead of executing POST.",
        },
        "input": {
            "type": "object",
            "description": "Single invocable action input object. If omitted, direct fields are collected into one input.",
        },
        "inputs": {
            "type": "array",
            "items": {"type": "object"},
            "description": "Raw Salesforce invocable action inputs array.",
        },
    }
    properties.update(meta.get("properties", {}))
    return {
        "type": "object",
        "properties": properties,
        "additionalProperties": True,
    }
